[package]
name = "utils"
version = "0.1.0"
authors = ["malefo.yun <784479660@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = "0.4.5"

#[profile.release]
#lto = true
#opt-level = 's'